//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string image { get; set; }
        public Nullable<int> typeOfCustomerId { get; set; }
    
        public virtual TypeOfCustomer TypeOfCustomer { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
