//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntrySlip
    {
        public EntrySlip()
        {
            this.EntrySlipDetails = new HashSet<EntrySlipDetail>();
        }
    
        public int id { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> supplierId { get; set; }
        public Nullable<bool> isPay { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<EntrySlipDetail> EntrySlipDetails { get; set; }
    }
}
