//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int id { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<bool> isPay { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
