//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.EntrySlipDetails = new HashSet<EntrySlipDetail>();
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public string image { get; set; }
        public Nullable<int> supplierId { get; set; }
        public Nullable<int> sizeId { get; set; }
        public Nullable<int> colorId { get; set; }
        public Nullable<int> materialId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> requimate { get; set; }
        public Nullable<int> remate { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        public virtual ICollection<EntrySlipDetail> EntrySlipDetails { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual Material Material { get; set; }
        public virtual Size Size { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
